<?php
	
	namespace hiweb\components\Fields\Types\Select;
	
	
	use hiweb\components\Fields\Field;
	
	
	class Field_Select extends Field{
		
		protected $options_class = '\hiweb\components\Fields\Types\Select\Field_Select_Options';
		
		public function get_css(){
			return [
				HIWEB_DIR_VENDOR . '/selectize.js/css/selectize.css',
			];
		}
		
		
		public function get_js(){
			return [
				'jquery-ui-sortable',
				HIWEB_DIR_VENDOR . '/selectize.js/js/standalone/selectize.min.js',
				__DIR__ . '/Field_Select.min.js'
			];
		}
		
		/**
		 * @return Field_Select_Options
		 */
		public function options(){
			return parent::options(); // TODO: Change the autogenerated stub
		}
		
		
		public function get_admin_html( $value = null, $name = null ){
			ob_start();
			include __DIR__.'/template.php';
			return ob_get_clean();
		}
		
	}