<?php

	namespace hiweb\components\Fields\Types\Repeat;


	use hiweb\components\Fields\Field;
	use hiweb\core\Cache\CacheFactory;


	class Field_Repeat extends Field{

		protected $options_class = '\hiweb\components\Fields\Types\Repeat\Field_Repeat_Options';


		public function get_css(){
			return [ __DIR__ . '/field-repeat.css' ];
		}


		public function get_js(){
			return [ HIWEB_DIR_VENDOR . '/vue/vue.min.js', HIWEB_DIR_VENDOR . '/deepMerge/deepMerge.min.js', __DIR__ . '/field-repeat.min.js' ];
		}


		public function get_sanitize_admin_value( $value ){
			if( !is_array( $value ) ){
				return [];
			}
			return $value;
		}


		/**
		 * @return Field_Repeat_Options
		 */
		public function Options(){
			return parent::Options(); // TODO: Change the autogenerated stub
		}


		/**
		 * @param $value_array
		 * @return Field_Repeat_Value
		 */
		public function Value( $value_array ){
			$key = md5( json_encode( $value_array ) );
			return CacheFactory::get( $key, __METHOD__, function(){
				return new Field_Repeat_Value( $this, func_get_arg( 0 ) );
			}, [ $value_array ] )->get_value();
		}


		public function get_admin_html( $value = null, $name = null ){
			ob_start();
			include __DIR__ . '/templates/template.php';
			return ob_get_clean();
		}

	}