<?php
	
	namespace hiweb\components\Fields\Types\Textarea;
	
	
	use hiweb\components\Fields\Field;
	
	
	class Field_Textarea extends Field{
		
		
		protected $options_class = '\hiweb\components\Fields\Types\Textarea\Field_Textarea_Options';
		
		/**
		 * @return Field_Textarea_Options
		 */
		public function Options(){
			return parent::Options(); // TODO: Change the autogenerated stub
		}
		
		
		public function get_css(){
			return [__DIR__.'/Style.css'];
		}
		
		
		public function get_admin_html( $value = null, $name = null ){
			ob_start();
			include __DIR__ . '/template.php';
			return ob_get_clean();
		}
		
	}